[package]
name = "chip8"
version = "0.1.0"
authors = ["Starr Horne <starr@chromahq.com>"]

[dependencies]
rand = "0.3.15"

[dependencies.sdl2]
version = "0.30"
default-features = false
features = ["gfx"]
